# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1445883220);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1445883340);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1445964074);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1445883100);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1445882980);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1445882740);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.defaultenginename", "Yahoo");
user_pref("browser.search.order.1", "Yahoo");
user_pref("browser.search.order.2", "Ixquick");
user_pref("browser.search.order.3", "Startpage");
user_pref("browser.search.order.4", "DuckDuckGo");
user_pref("browser.search.region", "IN");
user_pref("browser.search.selectedEngine", "Yahoo");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151017150840");
user_pref("browser.slowStartup.averageTime", 1995);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "http://www.linuxmint.com/start/rebecca");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":2}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1445882682572");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1445882700054");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1445969100054");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1445882631380");
user_pref("datareporting.policy.firstRunTime", "1445622042083");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2355);
user_pref("datareporting.sessions.current.main", 41);
user_pref("datareporting.sessions.current.sessionRestored", 2035);
user_pref("datareporting.sessions.current.startTime", "1445965178541");
user_pref("datareporting.sessions.current.totalTime", 12);
user_pref("datareporting.sessions.currentIndex", 34);
user_pref("datareporting.sessions.previous.30", "{\"s\":1445882619408,\"a\":101,\"t\":1487,\"c\":true,\"m\":30,\"fp\":1725,\"sr\":1958}");
user_pref("datareporting.sessions.previous.31", "{\"s\":1445884110125,\"a\":17,\"t\":211,\"c\":true,\"m\":1166,\"fp\":3245,\"sr\":3497}");
user_pref("datareporting.sessions.previous.32", "{\"s\":1445884326644,\"a\":57,\"t\":1427,\"c\":true,\"m\":41,\"fp\":2103,\"sr\":2006}");
user_pref("datareporting.sessions.previous.33", "{\"s\":1445963951512,\"a\":88,\"t\":1121,\"c\":true,\"m\":1581,\"fp\":5613,\"sr\":5566}");
user_pref("datareporting.sessions.prunedIndex", 29);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"41.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"41.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "mint-search-enhancer%40linuxmint.com:1.0,%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D:1.0.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:41.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1445883224);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150902.02");
user_pref("extensions.lastAppVersion", "41.0.2");
user_pref("extensions.lastPlatformVersion", "41.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"mint-search-enhancer@linuxmint.com\":{\"d\":\"/usr/lib/firefox/browser/extensions/mint-search-enhancer@linuxmint.com\",\"e\":true,\"v\":\"1.0\",\"st\":1417041188000,\"mt\":1346324837000},\"{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\",\"e\":true,\"v\":\"1.0.7\",\"st\":1417041189000,\"mt\":1336770080000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"33.0\",\"st\":1445095967000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"33.0\",\"st\":1445774351000,\"mt\":1445095638000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"33.0\",\"st\":1445095966000}}}");
user_pref("gecko.buildID", "20151017150840");
user_pref("gecko.mstone", "41.0.2");
user_pref("keyword.URL", "https://duckduckgo.com/?t=lm&q=");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1445882755);
user_pref("media.gmp-gmpopenh264.version", "1.4");
user_pref("media.gmp-manager.buildID", "20151017150840");
user_pref("media.gmp-manager.lastCheck", 1445882694);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.protocol-handler.app.apt", "/usr/bin/apturl");
user_pref("network.protocol-handler.app.apt+http", "/usr/bin/apturl");
user_pref("network.protocol-handler.warn-external.apt", true);
user_pref("network.protocol-handler.warn-external.apt+http", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 47744);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1445965178);
user_pref("toolkit.telemetry.cachedClientID", "a140ef1a-8b66-4584-8ecc-4056465e5102");
user_pref("toolkit.telemetry.previousBuildID", "20141013200257");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
